LMS/Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LMS.Models
{
    public class Member
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required, DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfBirth { get; set; }
        [Required, Display(Name ="Membership")]
        public int MembershipID { get; set; }
        public virtual Membership Membership { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
    }
}

LMS/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;
using System.Data.Entity.Validation;
using System.Text;
using Microsoft.AspNet.Identity;

namespace LMS.Controllers
{
    [Authorize]
    public class LoansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(int? page, bool? showReturnedBooks)
        {
			int pageSize = 10;
			int pageNumber = (page ?? 1);
            ViewBag.ShowReturnedBooks = showReturnedBooks;

            var loans = db.Loans.Include(l => l.BookCopy)
                .Include(l => l.LoanType)
                .Include(l => l.Member);

            if (showReturnedBooks != true)
            {
                loans = loans.Where(b => b.ReturnedOn == null);
            }

            var loanslist = loans.OrderByDescending(l => l.IssuedOn.Year)
                .ThenByDescending(l => l.IssuedOn.Month)
                .ThenByDescending(l => l.IssuedOn.Day)
                .ThenBy(l => l.BookCopy.Book.Name)
                .ToPagedList(pageNumber, pageSize);

            return View(loanslist);
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy copy = db.BookCopies.Where(c => c.Available && c.ID == id).FirstOrDefault();
            if (copy == null)
            {
                return HttpNotFound();
            }

            ViewBag.BookCopy = copy;

            ViewBag.BookCopyID = id;
            ViewBag.LoanTypeID = new SelectList(db.LoanTypes, "ID", "Name");

            var members = db.Members.Select(m => new {
                ID = m.ID,
                Name = m.ID + " - " +  m.FirstName + " " + m.MiddleName + " "+ m.LastName
            }).ToList();
            ViewBag.MemberID = new SelectList(members, "ID", "Name");

            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? id, [Bind(Include = "MemberID,LoanTypeID,BookCopyID")] Loan loan)
        {
            if (id == null || id != loan.BookCopyID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BookCopy copy = db.BookCopies.Where(c => c.Available && c.ID == id).FirstOrDefault();
            if (copy == null)
            {
                return HttpNotFound();
            }

            ViewBag.BookCopy = copy;

            loan.BookCopy = copy;
            var loanType = db.LoanTypes.Find(loan.LoanTypeID);

            var dateIssued = DateTime.Now;
            var dueDate = dateIssued.AddDays(loanType.Duration);
            var dateReturned = DateTime.MinValue;
            loan.IssuedOn = dateIssued;
            loan.DueDate = dueDate;
            loan.LoanCharge = loanType.Duration * copy.Book.Charge;
            loan.PenaltyCharge = 0;
            loan.LoanedBy = this.db.Users.Find(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                db.Loans.Add(loan);
                copy.Available = false;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = loan.ID });
            }

            ViewBag.BookCopyID = id;
            ViewBag.LoanTypeID = new SelectList(db.LoanTypes, "ID", "Name");

            var members = db.Members.Select(m => new {
                ID = m.ID,
                Name = m.ID + " - " + m.FirstName + " " + m.MiddleName + " " + m.LastName
            }).ToList();
            ViewBag.MemberID = new SelectList(members, "ID", "Name");
            return View(loan);
        }

        
        public ActionResult Return(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy copy = db.BookCopies.Where(c => !c.Available && c.ID == id).FirstOrDefault();
            Loan loan = copy.Loans.LastOrDefault();
            if (copy == null || loan == null)
            {
                return HttpNotFound();
            }

            loan.ReturnedOn = DateTime.Now;
            TimeSpan difference = loan.ReturnedOn.GetValueOrDefault() - loan.DueDate.GetValueOrDefault();
            loan.PenaltyCharge = loan.ReturnedOn < loan.DueDate ? 0 : Math.Round(difference.TotalDays) * copy.Book.PenaltyCharge;
            copy.Available = true;
            db.SaveChanges();

            return RedirectToAction("Details", new { id = loan.ID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;

namespace LMS.Controllers
{
    [Authorize]
    public class MembersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(string searchString, int? page)
        {
			int pageSize = 10;
			int pageNumber = (page ?? 1);
            var members = db.Members.Include(m => m.Membership);

            ViewBag.SearchString = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();

                int number = 0;
                int.TryParse(searchString, out number);

                if (number > 0)
                {
                    members = members.Where(m => m.ID.ToString() == searchString);
                }else
                {
                    members = members.Where(m => m.FirstName.ToLower().Contains(searchString) || m.MiddleName.ToLower().Contains(searchString) || m.LastName.ToLower().Contains(searchString));
                }
            }

            return View(members.OrderBy(m => m.FirstName).ToPagedList(pageNumber, pageSize));
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        
        public ActionResult Create()
        {
            ViewBag.MembershipID = new SelectList(db.Memberships, "ID", "Name");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,MiddleName,LastName,DateOfBirth,MembershipID,Address,PhoneNumber")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MembershipID = new SelectList(db.Memberships, "ID", "Name", member.MembershipID);
            return View(member);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            ViewBag.MembershipID = new SelectList(db.Memberships, "ID", "Name", member.MembershipID);
            return View(member);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,MiddleName,LastName,DateOfBirth,MembershipID,Address,PhoneNumber")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MembershipID = new SelectList(db.Memberships, "ID", "Name", member.MembershipID);
            return View(member);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Views/Members/Create.cshtml
@model LMS.Models.Member

@{
    ViewBag.Title = "Member";
	ViewBag.TitleSmall = "Create";
}

<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create Member</h3>
            </div>

            @using (Html.BeginForm())
            {
                <div class="box-body">

                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					<div class="form-group">
						@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.DateOfBirth, "Date of Birth", htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.MembershipID, "Membership", htmlAttributes: new { @class = "control-label" })
						@Html.DropDownList("MembershipID", null, htmlAttributes: new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.MembershipID, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.PhoneNumber, "Phone Number", htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
					</div>

				</div>

                <div class="box-footer">
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-double-left"> </i> Back to List</a>
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Save</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/Members/Details.cshtml
@model LMS.Models.Member

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Member Details</h3>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>First Name</dt>
                    <dd> @Model.FirstName </dd>
                    <dt>Middle Name</dt>
                    <dd> @Model.MiddleName </dd>
                    <dt>Last Name</dt>
                    <dd> @Model.LastName </dd>
                    <dt>Membership Type</dt>
                    <dd> @Model.Membership.Name </dd>
                    <dt>Date of Birth</dt>
                    <dd> @Model.DateOfBirth.GetValueOrDefault().ToShortDateString() </dd>
                    <dt>Address</dt>
                    <dd> @Model.Address </dd>
                    <dt>Phone Number</dt>
                    <dd> @Model.PhoneNumber </dd>
                    <dt>Current Active Loans</dt>
                    <dd> @Model.Loans.Where(l => l.ReturnedOn == null).Count() </dd>
                    <dt>Total Loans to Date</dt>
                    <dd> @Model.Loans.Count() </dd>
                    <dt>Loans During Last 31 days</dt>
                    <dd> @Model.Loans.Where(l => l.IssuedOn >= DateTime.Now.AddDays(-31)).Count() </dd>
                </dl>
                <p>
                    <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", new { id=Model.ID })"><i class="fa fa-edit"> </i> Edit</a>
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-left"> </i>  Back to List</a>
                </p>

                <h4>Loans During Last 31 Days</h4>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Book Name</th>
                            <th>Copy Number</th>
                            <th>Loan Type</th>
                            <th>Issued On</th>
                            <th>Due Date</th>
                            <th>Returned On</th>
                            <th>Loan Charge</th>
                            <th>Penalty Charge</th>
                            <th>Loaned By</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var loanItems = Model.Loans.Where(l => l.IssuedOn >= DateTime.Now.AddDays(-31)).ToList();
                        }
                        @foreach (var item in loanItems)
                        {
                            <tr>
                                <td>@item.BookCopy.Book.Name</td>
                                <td>@item.BookCopy.ID</td>
                                <td>@item.LoanType.Name</td>
                                <td>@item.IssuedOn.ToShortDateString()</td>
                                <td>@item.DueDate.GetValueOrDefault().ToShortDateString()</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn == null)
                                        {
                                            <span class="label label-warning">Not Returned</span>
                                        }
                                        else
                                        {
                                            @item.ReturnedOn.GetValueOrDefault().ToShortDateString()
                                        }
                                    }
                                </td>
                                <td>@item.LoanCharge</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn != null)
                                        {
                                            @item.PenaltyCharge
                                        }
                                    }
                                </td>
                                <td>@item.LoanedBy.FullName</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn == null)
                                        {
                                            <a class="btn btn-success btn-sm" href="@Url.Action("Return", "Loans", new { id = item.BookCopy.ID })"><i class="fa fa-cart-arrow-down"> </i> Return Book</a>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <h4>Active Loans</h4>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Book Name</th>
                            <th>Copy Number</th>
                            <th>Loan Type</th>
                            <th>Issued On</th>
                            <th>Due Date</th>
                            <th>Returned On</th>
                            <th>Loan Charge</th>
                            <th>Penalty Charge</th>
                            <th>Loaned By</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var loans = Model.Loans.Where(l => l.ReturnedOn == null).ToList();
                        }
                        @foreach (var item in loans)
                        {
                            <tr>
                                <td>@item.BookCopy.Book.Name</td>
                                <td>@item.BookCopy.ID</td>
                                <td>@item.LoanType.Name</td>
                                <td>@item.IssuedOn.ToShortDateString()</td>
                                <td>@item.DueDate.GetValueOrDefault().ToShortDateString()</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn == null)
                                        {
                                            @: <span class="label label-warning">Not Returned</span>
                                    }
                                        else
                                        {
                                            @item.ReturnedOn.GetValueOrDefault().ToShortDateString()
                                    }
                                    }
                                </td>
                                <td>@item.LoanCharge</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn != null)
                                        {
                                            @item.PenaltyCharge
                                    }
                                    }
                                </td>
                                <td>@item.LoanedBy.FullName</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn == null)
                                        {
                                            <a class="btn btn-success btn-sm" href="@Url.Action("Return", "Loans", new { id = item.BookCopy.ID })"><i class="fa fa-cart-arrow-down"> </i> Return Book</a>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

LMS/Views/Members/Edit.cshtml
@model LMS.Models.Member

@{
    ViewBag.Title = "Member";
	ViewBag.TitleSmall = "Edit";
}

<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit Member</h3>
            </div>

            @using (Html.BeginForm())
            {
                <div class="box-body">

                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@Html.HiddenFor(model => model.ID)

					<div class="form-group">
						@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.DateOfBirth, "Date of Birth", htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.MembershipID, "Membership", htmlAttributes: new { @class = "control-label" })
						@Html.DropDownList("MembershipID", null, htmlAttributes: new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.MembershipID, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.PhoneNumber, "Phone Number", htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
					</div>

				</div>

                <div class="box-footer">
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-double-left"> </i> Back to List</a>
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Save</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/Members/Index.cshtml
@model PagedList.IPagedList<LMS.Models.Member>
@using PagedList.Mvc

@{
    ViewBag.Title = "Member";
	ViewBag.TitleSmall = "All";
}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <a class="btn btn-primary pull-right" href="@Url.Action("Create")"><i class="fa fa-plus"></i> Add</a>
                @using (Html.BeginForm("Index", "Members", FormMethod.Get))
                {
                    <div class="col-sm-4">
                        <div class="input-group add-on">
                            @Html.TextBox("SearchString", ViewBag.SearchString as string, new { @class = "form-control", @placeholder = "Search by MemberID, Member Name..." })
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="box-body">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                <table class="table table-bordered">
					<thead>
						<tr>
                            <th>
                                ID
                            </th>
							<th>
								First Name
							</th>
							<th>
								Middle Name
							</th>
							<th>
								Last Name
							</th>
                            <th>
                                Membership Type
                            </th>
                            <th>
                                Current Loans
                            </th>
                            <th>
                                Total Loans Allowed
                            </th>
							<th></th>
						</tr>
					</thead>
					<tbody>

						@foreach (var item in Model) {
							<tr>
                                <th>
                                    @item.ID
                                </th>
								<td>
									@Html.DisplayFor(modelItem => item.FirstName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.MiddleName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.LastName)
								</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Membership.Name)
                                </td>
                                <td>
                                    @item.Loans.Where(l => l.ReturnedOn == null).Count()
                                </td>
                                <td>
                                    @item.Membership.MaxLoans
                                </td>
								<td>
									<a class="btn btn-primary btn-sm" href="@Url.Action("Edit", new { id=item.ID })"><i class="fa fa-edit"> </i> Edit</a>
                                    <a class="btn btn-warning btn-sm" href="@Url.Action("Details", new { id=item.ID })"><i class="fa fa-info"> </i> Details</a>
								</td>
							</tr>
						}
					</tbody>
				</table>
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
			</div>
			<div class="box-footer clearfix">
                <div class="pull-right">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SearchString = ViewBag.SearchString }))
                </div>
            </div>
		</div>
	</div>
</div>