LMS/Models/BookCopy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LMS.Models
{
    public class BookCopy
    {
        public BookCopy()
        {
            this.Available = true;
        }

        public int ID { get; set; }
        [Required, Display(Name ="Book")]
        public int BookID { get; set; }
        public virtual Book Book { get; set; }
        [Required]
        public string Location { get; set; }
        [Editable(false)]
        public Boolean Available { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }

        [Editable(false), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? AddedOn { get; set; }
    }
}

LMS/Controllers/BookCopiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;

namespace LMS.Controllers
{
    public class BookCopiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(string searchString, int? page)
        {
			int pageSize = 10;
			int pageNumber = (page ?? 1);

            var bookCopies = db.BookCopies.Include(b => b.Book);

            ViewBag.SearchString = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();

                int number = 0;
                int.TryParse(searchString, out number);

                if (number > 0)
                {
                    bookCopies = bookCopies.Where(bc => bc.ID.ToString() == searchString);
                }
                else
                {
                    bookCopies = bookCopies.Where(bc => bc.Book.Name.ToLower().Contains(searchString) || bc.Book.Publisher.Name.ToLower().Contains(searchString) || bc.Book.Authors.Any(author => author.FirstName.ToLower().Contains(searchString) || author.MiddleName.ToLower().Contains(searchString) || author.LastName.ToLower().Contains(searchString)));
                }
            }

            return View(bookCopies.OrderByDescending(m => m.Book.Name).ToPagedList(pageNumber, pageSize));
        }

        // GET: BookCopies/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy bookCopy = db.BookCopies.Find(id);
            if (bookCopy == null)
            {
                return HttpNotFound();
            }
            return View(bookCopy);
        }

        
        [Authorize]
        public ActionResult Create(int? SelectedBookID)
        {
            ViewBag.BookID = new SelectList(db.Books, "ID", "Name", SelectedBookID);
            return View();
        }

        
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,BookID,Location,Available")] BookCopy bookCopy)
        {
            if (ModelState.IsValid)
            {
                bookCopy.AddedOn = DateTime.Now;
                db.BookCopies.Add(bookCopy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookID = new SelectList(db.Books, "ID", "Name", bookCopy.BookID);
            return View(bookCopy);
        }

        
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy bookCopy = db.BookCopies.Find(id);
            if (bookCopy == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookID = new SelectList(db.Books, "ID", "Name", bookCopy.BookID);
            return View(bookCopy);
        }

        
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BookID,Location,Available")] BookCopy bookCopy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookCopy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookID = new SelectList(db.Books, "ID", "Name", bookCopy.BookID);
            return View(bookCopy);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;
using System.Data.Entity.Validation;
using System.Text;
using Microsoft.AspNet.Identity;

namespace LMS.Controllers
{
    [Authorize]
    public class LoansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(int? page, bool? showReturnedBooks)
        {
			int pageSize = 10;
			int pageNumber = (page ?? 1);
            ViewBag.ShowReturnedBooks = showReturnedBooks;

            var loans = db.Loans.Include(l => l.BookCopy)
                .Include(l => l.LoanType)
                .Include(l => l.Member);

            if (showReturnedBooks != true)
            {
                loans = loans.Where(b => b.ReturnedOn == null);
            }

            var loanslist = loans.OrderByDescending(l => l.IssuedOn.Year)
                .ThenByDescending(l => l.IssuedOn.Month)
                .ThenByDescending(l => l.IssuedOn.Day)
                .ThenBy(l => l.BookCopy.Book.Name)
                .ToPagedList(pageNumber, pageSize);

            return View(loanslist);
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy copy = db.BookCopies.Where(c => c.Available && c.ID == id).FirstOrDefault();
            if (copy == null)
            {
                return HttpNotFound();
            }

            ViewBag.BookCopy = copy;

            ViewBag.BookCopyID = id;
            ViewBag.LoanTypeID = new SelectList(db.LoanTypes, "ID", "Name");

            var members = db.Members.Select(m => new {
                ID = m.ID,
                Name = m.ID + " - " +  m.FirstName + " " + m.MiddleName + " "+ m.LastName
            }).ToList();
            ViewBag.MemberID = new SelectList(members, "ID", "Name");

            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? id, [Bind(Include = "MemberID,LoanTypeID,BookCopyID")] Loan loan)
        {
            if (id == null || id != loan.BookCopyID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BookCopy copy = db.BookCopies.Where(c => c.Available && c.ID == id).FirstOrDefault();
            if (copy == null)
            {
                return HttpNotFound();
            }

            ViewBag.BookCopy = copy;

            loan.BookCopy = copy;
            var loanType = db.LoanTypes.Find(loan.LoanTypeID);

            var dateIssued = DateTime.Now;
            var dueDate = dateIssued.AddDays(loanType.Duration);
            var dateReturned = DateTime.MinValue;
            loan.IssuedOn = dateIssued;
            loan.DueDate = dueDate;
            loan.LoanCharge = loanType.Duration * copy.Book.Charge;
            loan.PenaltyCharge = 0;
            loan.LoanedBy = this.db.Users.Find(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                db.Loans.Add(loan);
                copy.Available = false;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = loan.ID });
            }

            ViewBag.BookCopyID = id;
            ViewBag.LoanTypeID = new SelectList(db.LoanTypes, "ID", "Name");

            var members = db.Members.Select(m => new {
                ID = m.ID,
                Name = m.ID + " - " + m.FirstName + " " + m.MiddleName + " " + m.LastName
            }).ToList();
            ViewBag.MemberID = new SelectList(members, "ID", "Name");
            return View(loan);
        }

        
        public ActionResult Return(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy copy = db.BookCopies.Where(c => !c.Available && c.ID == id).FirstOrDefault();
            Loan loan = copy.Loans.LastOrDefault();
            if (copy == null || loan == null)
            {
                return HttpNotFound();
            }

            loan.ReturnedOn = DateTime.Now;
            TimeSpan difference = loan.ReturnedOn.GetValueOrDefault() - loan.DueDate.GetValueOrDefault();
            loan.PenaltyCharge = loan.ReturnedOn < loan.DueDate ? 0 : Math.Round(difference.TotalDays) * copy.Book.PenaltyCharge;
            copy.Available = true;
            db.SaveChanges();

            return RedirectToAction("Details", new { id = loan.ID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Views/BookCopies/Create.cshtml
@model LMS.Models.BookCopy

@{
    ViewBag.Title = "Book Copy";
	ViewBag.TitleSmall = "Create";
}

<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create Book Copy</h3>
            </div>

            @using (Html.BeginForm())
            {
                <div class="box-body">

                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					<div class="form-group">
						@Html.LabelFor(model => model.BookID, "BookID", htmlAttributes: new { @class = "control-label" })
						@Html.DropDownList("BookID", null, htmlAttributes: new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.BookID, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
					</div>

				</div>

                <div class="box-footer">
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-double-left"> </i> Back to List</a>
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Save</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/BookCopies/Details.cshtml
@model LMS.Models.BookCopy

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Book Copy details</h3>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>ISBN</dt><dd> @Model.Book.ISBN </dd>
                    <dt>Name</dt><dd> @Model.Book.Name </dd>
                    <dt>Press</dt><dd> @Model.Book.Press.Name </dd>
                    <dt>Publisher</dt><dd> @Model.Book.Publisher.Name </dd>
                    <dt>Published Date</dt><dd> @Model.Book.PublishedDate.GetValueOrDefault().ToShortDateString()</dd>
                    <dt>Charge</dt><dd> @Model.Book.Charge</dd>
                    <dt>Penalty Charge</dt><dd> @Model.Book.PenaltyCharge</dd>
                </dl>
                <hr />
                <dl class="dl-horizontal">
                    <dt>Copy Number</dt>
                    <dd> @Model.ID </dd>
                    <dt>Available</dt>
                    <dd>
                        @{
                            if (Model.Available)
                            {
                                @: Yes
                            }
                            else
                            {
                                @: No
                            }
                        }
                    </dd>
                    <dt>Location</dt>
                    <dd> @Model.Location </dd>
                </dl>
                <hr />
                <p>
                    @{
                        if (Model.Available)
                        {
                            <a class="btn btn-success btn-sm" href="@Url.Action("Create", "Loans", new { id = Model.ID })"><i class="fa fa-cart-plus"> </i> Provide on Loan</a>
                        }
                        else
                        {
                            <a class="btn btn-success btn-sm" href="@Url.Action("Return", "Loans", new { id = Model.ID })"><i class="fa fa-cart-arrow-down"> </i> Return Book</a>
                        }
                    }
                    <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", new { id=Model.ID })"><i class="fa fa-edit"> </i> Edit</a>
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-left"> </i>  Back to List</a>
                </p>

                <h4>Loans</h4>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Member ID</th>
                            <th>Member Name</th>
                            <th>Loan Type</th>
                            <th>Issued On</th>
                            <th>Due Date</th>
                            <th>Returned On</th>
                            <th>Loan Charge</th>
                            <th>Penalty Charge</th>
                            <th>Loaned By</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Loans.OrderByDescending(l => l.IssuedOn).ToList())
                        {
                            <tr>
                                <td>@item.MemberID</td>
                                <td>@item.Member.FirstName @item.Member.MiddleName @item.Member.LastName</td>
                                <td>@item.LoanType.Name</td>
                                <td>@item.IssuedOn.ToShortDateString()</td>
                                <td>@item.DueDate.GetValueOrDefault().ToShortDateString()</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn == null)
                                        {
                                            @: <span class="label label-warning">Not Returned</span>
                                        }
                                        else
                                        {
                                            @item.ReturnedOn.GetValueOrDefault().ToShortDateString()
                                        }
                                    }
                                </td>
                                <td>@item.LoanCharge</td>
                                <td>
                                    @{
                                        if (item.ReturnedOn != null)
                                        {
                                            @item.PenaltyCharge
                                        }
                                    }
                                </td>
                                <td>@item.LoanedBy.FullName</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

LMS/Views/BookCopies/Edit.cshtml
@model LMS.Models.BookCopy

@{
    ViewBag.Title = "Book Copy";
	ViewBag.TitleSmall = "Edit";
}

<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit Book Copy</h3>
            </div>

            @using (Html.BeginForm())
            {
                <div class="box-body">

                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@Html.HiddenFor(model => model.ID)

					<div class="form-group">
						@Html.LabelFor(model => model.BookID, "BookID", htmlAttributes: new { @class = "control-label" })
						@Html.DropDownList("BookID", null, htmlAttributes: new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.BookID, "", new { @class = "text-danger" })
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
						@Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
					</div>

				</div>

                <div class="box-footer">
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-double-left"> </i> Back to List</a>
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Save</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/BookCopies/Index.cshtml
@model PagedList.IPagedList<LMS.Models.BookCopy>
@using PagedList.Mvc

@{
    ViewBag.Title = "Book Copy";
	ViewBag.TitleSmall = "All";
}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <a class="btn btn-primary pull-right" href="@Url.Action("Create")"><i class="fa fa-plus"></i> Add</a>
                @using (Html.BeginForm("Index", "BookCopies", FormMethod.Get))
                {
                    <div class="col-sm-4">
                        <div class="input-group add-on">
                            @Html.TextBox("SearchString", ViewBag.SearchString as string, new { @class = "form-control", @placeholder = "Search by Book Name, Publisher, Author..." })
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="box-body">
                <table class="table table-bordered">
					<thead>
						<tr>
							<th>
								Book Name
							</th>
							<th>
								Publisher Name
							</th>
							<th>
								Authors
							</th>
							<th>
								Copy Number
							</th>
							<th>
								Location
							</th>
							<th>
								Available
							</th>
							<th></th>
						</tr>
					</thead>
					<tbody>

						@foreach (var item in Model)
                        {
							<tr>
								<td>
									@Html.DisplayFor(modelItem => item.Book.Name)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Book.Publisher.Name)
								</td>
								<td>
                                    <ul>
                                        @{
                                            foreach (var author in item.Book.Authors)
                                            {
                                                @:
                                                <li>@author.FirstName @author.MiddleName @author.LastName</li>
                                            }
                                        }
                                    </ul>
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.ID)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Location)
								</td>
								<td>
									@{
                                        if (item.Available)
                                        {
                                            @: <span class="label label-success">Available</span>
                                        }
                                        else
                                        {
                                            @: <span class="label label-warning">On Loan</span>
                                        }
									}
								</td>
								<td>
                                    @{
                                        if (item.Available)
                                        {
                                            <a class="btn btn-success btn-sm" href="@Url.Action("Create", "Loans", new { id = item.ID })"><i class="fa fa-cart-plus"> </i> Provide on Loan</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success btn-sm" href="@Url.Action("Return", "Loans", new { id = item.ID })"><i class="fa fa-cart-arrow-down"> </i> Return Book</a>
                                        }
                                    }
									<a class="btn btn-primary btn-sm" href="@Url.Action("Edit", new { id = item.ID })"><i class="fa fa-edit"> </i> Edit</a>
									<a class="btn btn-warning btn-sm" href="@Url.Action("Details", new { id = item.ID })"><i class="fa fa-info"> </i> Details</a>
								</td>
							</tr>
                        }
					</tbody>
				</table>
			</div>
			<div class="box-footer clearfix">
                <div class="pull-right">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SearchString = ViewBag.SearchString }))
                </div>
            </div>
		</div>
	</div>
</div>