LMS/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LMS.Models
{
    public class Book
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string ISBN { get; set; }
        [Required, Display(Name="Publisher")]
        public int PublisherID { get; set; }
        public virtual Publisher Publisher { get; set; }
        [Required, Display(Name = "Press")]
        public int PressID { get; set; }
        public virtual Press Press { get; set; }
        [Required, DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? PublishedDate { get; set; }
        [Required]
        public double Charge { get; set; }
        [Required]
        public double PenaltyCharge { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<BookCopy> Copies { get; set; }
    }
}

LMS/ViewModels/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LMS.ViewModels
{
    public class AssignedAuthorData
    {
        public int AuthorID { get; set; }
        public string Name { get; set; }
        public bool Assigned { get; set; }
    }

    public class AssignedCategoryData
    {
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public bool Assigned { get; set; }
    }
}

LMS/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;
using LMS.ViewModels;

namespace LMS.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(string searchString, bool? copyAvailable, int? sortOrder, int? page)
        {
			int pageSize = 10;
			int pageNumber = (page ?? 1);
            var books = db.Books.Include(b => b.Press).Include(b => b.Publisher).Include(b => b.Authors);

            ViewBag.SearchString = searchString;
            ViewBag.CopyAvailable = copyAvailable;
            ViewBag.SortOrderDesc = sortOrder == 1;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();
                books = books.Where(b => b.Name.ToLower().Contains(searchString) || b.Publisher.Name.ToLower().Contains(searchString) || b.Authors.Any(author => author.FirstName.ToLower().Contains(searchString) || author.MiddleName.ToLower().Contains(searchString) || author.LastName.ToLower().Contains(searchString)));
            }

            if(copyAvailable == true)
            {
                books = books.Where(b => b.Copies.Any(c => c.Available));
            }

            if (!ViewBag.SortOrderDesc)
            {
                books = books.OrderBy(b => b.PublishedDate);
            }
            else
            {
                books = books.OrderByDescending(b => b.PublishedDate);
            }

            return View(books.ToPagedList(pageNumber, pageSize));
        }

        
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.PressID = new SelectList(db.Press, "ID", "Name");
            ViewBag.PublisherID = new SelectList(db.Publishers, "ID", "Name");

            PopulateAssignedAuthorData(null);
            PopulateAssignedCategoryData(null);
            return View();
        }

        
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,ISBN,PublisherID,PressID,PublishedDate,Charge,PenaltyCharge")] Book book, string[] selectedAuthors, string[] selectedCategories)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                UpdateAssignedAuthorData(selectedAuthors, ref book);
                UpdateAssignedCategoryData(selectedCategories, ref book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PressID = new SelectList(db.Press, "ID", "Name", book.PressID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "ID", "Name", book.PublisherID);
            PopulateAssignedAuthorData(null);
            PopulateAssignedCategoryData(null);

            return View(book);
        }

        
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.PressID = new SelectList(db.Press, "ID", "Name", book.PressID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "ID", "Name", book.PublisherID);
            PopulateAssignedAuthorData(book);
            PopulateAssignedCategoryData(book);
            return View(book);
        }

        
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,ISBN,PublisherID,PressID,PublishedDate,Charge,PenaltyCharge")] Book book, string[] selectedAuthors, string[] selectedCategories)
        {
            if (db.Entry(book).State == EntityState.Detached)
            {
                db.Books.Attach(book);
            }

            db.Entry(book).Collection(b => b.Authors).Load();
            db.Entry(book).Collection(b => b.Categories).Load();

            if (ModelState.IsValid)
            {
                UpdateAssignedAuthorData(selectedAuthors, ref book);
                UpdateAssignedCategoryData(selectedCategories, ref book);
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PressID = new SelectList(db.Press, "ID", "Name", book.PressID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "ID", "Name", book.PublisherID);
            PopulateAssignedAuthorData(book);
            PopulateAssignedCategoryData(book);
            return View(book);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void PopulateAssignedAuthorData(Book book)
        {
            var allAuthors = db.Authors;
            var bookAuthors = new HashSet<int>();
            if (book != null)
            {
                bookAuthors = new HashSet<int>(book.Authors.Select(s => s.ID));
            }

            var viewModel = new List<AssignedAuthorData>();
            foreach (Author author in allAuthors)
            {
                viewModel.Add(new AssignedAuthorData
                {
                    AuthorID = author.ID,
                    Name = author.FirstName + " " + author.MiddleName + " " + author.LastName,
                    Assigned = bookAuthors.Contains(author.ID)
                });
            }

            ViewBag.Authors= viewModel;
        }

        private void UpdateAssignedAuthorData(string[] selectedAuthors, ref Book book)
        {
            if(book.Authors == null)
            {
                book.Authors = new List<Author>();
            }

            if (selectedAuthors == null)
            {
                book.Authors = new List<Author>();
                return;
            }

            var selectedAuthorsHS = new HashSet<string>(selectedAuthors);
            var bookAuthors = new HashSet<int>(book.Authors.Select(c => c.ID));
            foreach (var author in db.Authors)
            {
                if (selectedAuthorsHS.Contains(author.ID.ToString()))
                {
                    if (!bookAuthors.Contains(author.ID))
                    {
                        book.Authors.Add(author);
                    }
                }
                else
                {
                    if (bookAuthors.Contains(author.ID))
                    {
                        book.Authors.Remove(author);
                    }
                }
            }
        }

        private void PopulateAssignedCategoryData(Book book)
        {
            var allCategories = db.Categories;
            var bookCategories = new HashSet<int>();
            if (book != null)
            {
                bookCategories = new HashSet<int>(book.Categories.Select(s => s.ID));
            }

            var viewModel = new List<AssignedCategoryData>();
            foreach (Category category in allCategories)
            {
                viewModel.Add(new AssignedCategoryData
                {
                    CategoryID = category.ID,
                    Name = category.Name,
                    Assigned = bookCategories.Contains(category.ID)
                });
            }

            ViewBag.Categories = viewModel;
        }

        private void UpdateAssignedCategoryData(string[] selectedCategories, ref Book book)
        {
            if (book.Categories == null)
            {
                book.Categories = new List<Category>();
            }

            if (selectedCategories == null)
            {
                book.Categories = new List<Category>();
                return;
            }

            var selectedCategoriesHS = new HashSet<string>(selectedCategories);
            var bookCategories = new HashSet<int>(book.Categories.Select(c => c.ID));
            foreach (var category in db.Categories)
            {
                if (selectedCategoriesHS.Contains(category.ID.ToString()))
                {
                    if (!bookCategories.Contains(category.ID))
                    {
                        book.Categories.Add(category);
                    }
                }
                else
                {
                    if (bookCategories.Contains(category.ID))
                    {
                        book.Categories.Remove(category);
                    }
                }
            }
        }
    }
}

LMS/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;
using System.Data.Entity.Validation;
using System.Text;
using Microsoft.AspNet.Identity;

namespace LMS.Controllers
{
    [Authorize]
    public class LoansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        public ActionResult Index(int? page, bool? showReturnedBooks)
        {
			int pageSize = 10;
			int pageNumber = (page ?? 1);
            ViewBag.ShowReturnedBooks = showReturnedBooks;

            var loans = db.Loans.Include(l => l.BookCopy)
                .Include(l => l.LoanType)
                .Include(l => l.Member);

            if (showReturnedBooks != true)
            {
                loans = loans.Where(b => b.ReturnedOn == null);
            }

            var loanslist = loans.OrderByDescending(l => l.IssuedOn.Year)
                .ThenByDescending(l => l.IssuedOn.Month)
                .ThenByDescending(l => l.IssuedOn.Day)
                .ThenBy(l => l.BookCopy.Book.Name)
                .ToPagedList(pageNumber, pageSize);

            return View(loanslist);
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy copy = db.BookCopies.Where(c => c.Available && c.ID == id).FirstOrDefault();
            if (copy == null)
            {
                return HttpNotFound();
            }

            ViewBag.BookCopy = copy;

            ViewBag.BookCopyID = id;
            ViewBag.LoanTypeID = new SelectList(db.LoanTypes, "ID", "Name");

            var members = db.Members.Select(m => new {
                ID = m.ID,
                Name = m.ID + " - " +  m.FirstName + " " + m.MiddleName + " "+ m.LastName
            }).ToList();
            ViewBag.MemberID = new SelectList(members, "ID", "Name");

            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? id, [Bind(Include = "MemberID,LoanTypeID,BookCopyID")] Loan loan)
        {
            if (id == null || id != loan.BookCopyID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BookCopy copy = db.BookCopies.Where(c => c.Available && c.ID == id).FirstOrDefault();
            if (copy == null)
            {
                return HttpNotFound();
            }

            ViewBag.BookCopy = copy;

            loan.BookCopy = copy;
            var loanType = db.LoanTypes.Find(loan.LoanTypeID);

            var dateIssued = DateTime.Now;
            var dueDate = dateIssued.AddDays(loanType.Duration);
            var dateReturned = DateTime.MinValue;
            loan.IssuedOn = dateIssued;
            loan.DueDate = dueDate;
            loan.LoanCharge = loanType.Duration * copy.Book.Charge;
            loan.PenaltyCharge = 0;
            loan.LoanedBy = this.db.Users.Find(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                db.Loans.Add(loan);
                copy.Available = false;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = loan.ID });
            }

            ViewBag.BookCopyID = id;
            ViewBag.LoanTypeID = new SelectList(db.LoanTypes, "ID", "Name");

            var members = db.Members.Select(m => new {
                ID = m.ID,
                Name = m.ID + " - " + m.FirstName + " " + m.MiddleName + " " + m.LastName
            }).ToList();
            ViewBag.MemberID = new SelectList(members, "ID", "Name");
            return View(loan);
        }

        
        public ActionResult Return(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookCopy copy = db.BookCopies.Where(c => !c.Available && c.ID == id).FirstOrDefault();
            Loan loan = copy.Loans.LastOrDefault();
            if (copy == null || loan == null)
            {
                return HttpNotFound();
            }

            loan.ReturnedOn = DateTime.Now;
            TimeSpan difference = loan.ReturnedOn.GetValueOrDefault() - loan.DueDate.GetValueOrDefault();
            loan.PenaltyCharge = loan.ReturnedOn < loan.DueDate ? 0 : Math.Round(difference.TotalDays) * copy.Book.PenaltyCharge;
            copy.Available = true;
            db.SaveChanges();

            return RedirectToAction("Details", new { id = loan.ID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Views/Books/Details.cshtml
@model LMS.Models.Book

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Book Details</h3>
            </div>
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>ISBN</dt>
                    <dd> @Model.ISBN </dd>
                    <dt>Name</dt>
                    <dd> @Model.Name </dd>
                    <dt>Press</dt>
                    <dd> @Model.Press.Name </dd>
                    <dt>Publisher</dt>
                    <dd> @Model.Publisher.Name </dd>
                    <dt>Published Date</dt>
                    <dd> @Model.PublishedDate.GetValueOrDefault().ToShortDateString()</dd>
                    <dt>Number of Copies</dt>
                    <dd> @Model.Copies.Count()</dd>
                    <dt>Authors</dt>
                    <dd>
                        <ul>
                            @{
                                foreach (var author in Model.Authors)
                                {
                                    <li>@author.FirstName @author.MiddleName @author.LastName</li>
                                }
                            }
                        </ul>
                    </dd>
                    <dt>Categories</dt>
                    <dd>
                        <ul>
                            @{
                                foreach (var category in Model.Categories)
                                {
                                    <li> @category.Name </li>
                                }
                            }
                        </ul>

                    </dd>
                </dl>
                <hr />
                <p>
                    <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", new { id=Model.ID })"><i class="fa fa-edit"> </i> Edit</a>
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index")"><i class="fa fa-angle-left"> </i>  Back to List</a>
                </p>

                <h4>Book Copies</h4>
                <a class="btn btn-primary pull-right" href="@Url.Action("Create", "BookCopies", new { SelectedBookID = Model.ID })"><i class="fa fa-plus"></i> Add</a>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Copy Number</th>
                            <th>Location</th>
                            <th>Available</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Copies)
                        {
                            <tr>
                                <td>@item.ID</td>
                                <td>@item.Location</td>
                                <td>
                                    @{
                                        if (item.Available)
                                        {
                                            @: <span class="label label-success">Available</span>
                                        }
                                        else
                                        {
                                            @: <span class="label label-warning">On Loan</span>
                                        }
                                    }
                                </td>
                                <td>
                                    @{
                                        if (item.Available)
                                        {
                                            <a class="btn btn-success btn-sm" href="@Url.Action("Create", "Loans", new { id = item.ID })"><i class="fa fa-cart-plus"> </i> Provide on Loan</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success btn-sm" href="@Url.Action("Return", "Loans", new { id = item.ID })"><i class="fa fa-cart-arrow-down"> </i> Return Book</a>
                                        }
                                    }
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", "BookCopies", new { id = item.ID })"><i class="fa fa-edit"> </i> Edit</a>
                                    <a class="btn btn-warning btn-sm" href="@Url.Action("Details", "BookCopies", new { id = item.ID })"><i class="fa fa-info"> </i> Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

LMS/Views/Books/Index.cshtml
@model PagedList.IPagedList<LMS.Models.Book>
@using PagedList.Mvc

@{
    ViewBag.Title = "Book";
	ViewBag.TitleSmall = "All";
}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-md-12">
                        <a class="btn btn-primary pull-right" href="@Url.Action("Create")"><i class="fa fa-plus"></i> Add</a>
                    </div>
                </div>
                <hr />
                <div class="row">
                    @using (Html.BeginForm("Index", "Books", FormMethod.Get, new { @id = "search-form" }))
                    {
                        <div class="col-sm-4">
                            <div class="input-group add-on">
                                @Html.TextBox("SearchString", ViewBag.SearchString as string, new { @class = "form-control", @placeholder = "Search by Book Name, Publisher, Author..." })
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="checkbox checkbox-inline">
                                <label>
                                    @Html.CheckBox("CopyAvailable", ViewBag.CopyAvailable as bool?) Having At Least 1 Copy Available
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-4">

                            <div class="form-group">
                                <label class="col-sm-4 text-right">Order By</label>
                                <div class="col-sm-8">
                                    <select class="form-control" name="SortOrder">
                                        <option value="0" @Html.Raw(!ViewBag.SortOrderDesc ? " selected=\"selected\"" : "")>Published Date - Oldest First</option>
                                        <option value="1" @Html.Raw(ViewBag.SortOrderDesc ? " selected=\"selected\"" : "")>Published Date - Newest First</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table class="table table-bordered">
					<thead>
						<tr>
                            <th>
                                ID
                            </th>
                            <th>
                                Book Name
                            </th>
                            <th>
                                ISBN
                            </th>
							<th>
								Press
							</th>
							<th>
								Publisher
							</th>
                            <th>
                                Authors
                            </th>
                            <th>
                                Categories
                            </th>
                            <th>
                                Copies
                            </th>
							<th>
								Published Date
							</th>
							<th></th>
						</tr>
					</thead>
					<tbody>

						@foreach (var item in Model) {
							<tr>
                                <td>
                                    @item.ID
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ISBN)
                                </td>
								<td>
									@Html.DisplayFor(modelItem => item.Press.Name)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Publisher.Name)
								</td>
                                <td>
                                    <ul>
                                        @{
                                            foreach (var author in item.Authors)
                                            {
                                                @: <li>@author.FirstName @author.MiddleName @author.LastName</li>
                                            }
                                        }
                                    </ul>
                                </td>
                                <td>
                                    <ul>
                                        @{
                                            foreach (var category in item.Categories)
                                            {
                                                @: <li> @category.Name </li>
                                            }
                                        }
                                    </ul>
                                </td>
                                <td>
                                    <span class="label label-success">@item.Copies.Where(c => c.Available).Count() Available</span> <br />
                                    <span class="label label-warning">@item.Copies.Where(c => !c.Available).Count() On-Loan</span>
                                </td>
								<td>
									@Html.DisplayFor(modelItem => item.PublishedDate)
								</td>
								<td>
									<a class="btn btn-primary btn-sm" href="@Url.Action("Edit", new { id=item.ID })"><i class="fa fa-edit"> </i> Edit</a>
                                    <a class="btn btn-warning btn-sm" href="@Url.Action("Details", new { id = item.ID })"><i class="fa fa-info"> </i> Details</a>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
			<div class="box-footer clearfix">
                <div class="pull-right">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SearchString = ViewBag.SearchString, CopyAvailable = ViewBag.CopyAvailable }))
                </div>
            </div>
		</div>
	</div>
</div>

@section Scripts{
<script type="text/javascript">
    $(document).ready(function(){
        $("#search-form").on('change', 'input, select', function () {
            $(this).closest('form').submit();
        });
    });
</script>   
}